### ISSUE TITLE
Recipe not available if adding mod in an existing game

### ISSUE THREAD

**Issue by nicolas-brousse** [InaccurateTank/hazard-stripes#1]
Hi, I already have concrete unlocked in my game save. So I can't access recipe added by this mod.

I found some people had similar issue with other mod, and they do a migration to resolve this. https://forums.factorio.com/viewtopic.php?p=556432#p556432

Do you think this kind of migration could also be applied to this mod?

**Comment by InaccurateTank** [comment]
I'd like to preface this with the fact I have *immense* disdain that Github ignored my notification settings for more than a year. Love only seeing this when going through my old repos...

*Anyway* I'd like to thank you for catching this and, as of commit 2f233da with the subsequent release of [v1.1.1](https://github.com/InaccurateTank/hazard-stripes/releases/tag/v1.1.1), this is fixed.

**Comment by nicolas-brousse** [comment]
Hi @InaccurateTank, thanks for your fix and feedback. And no worries for the delay due to not having receive any notification.

I'm not currently playing Factorio, but I still have the save I played when I opened this Issue, I'll try to have take time in the following days to test it.

**Comment by nicolas-brousse** [comment]
It works perfectly. Thanks again @InaccurateTank

**Comment by InaccurateTank** [comment]
Thanks for the confirm. I did test it on my machine prior to push, but you never really know what could happen.
